#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: Build my curl and busybox

on:
  #schedule:
  #  - cron: 0 20 * * *
   push:
     branches: 
       - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Set git identity
        run : |
            git config --global user.email "liwenjie119@126.com"
            git config --global user.name "liwenjie119"
            git submodule update --init --recursive
            
      - name: update software
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install tree  build-essential asciidoc autoconf libtool  binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint  golang device-tree-compiler bc ninja-build cmake
          sudo -E ln -s /usr/bin/ninja /usr/bin/ninja-build
          ulimit -n 40960
          ulimit -a
          #wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
          #sudo -E unzip ninja-linux.zip -d /usr/local/bin/
          #sudo -E update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
          #curl https://sh.rustup.rs -o rustup-init.sh
          #chmod 777 rustup-init.sh
          #bash rustup-init.sh -y 
          #source $HOME/.cargo/env
          #rustup install stable 
          #rustup default stable 
          #rustup target add aarch64-linux-android arm-linux-androideabi armv7-linux-androideabi i686-linux-android x86_64-linux-android 

          #sudo -E apt-get -y install -f  gcc-aarch64-linux-gnu
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: update Commits
        run: |
          ./update.sh
          
      - name: make busybox
        run: |
            ./busybox.sh
            
      - name: make curl
        run: ./build.sh
        

      - name: Assemble artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./curl-static/arm64-v8a/bin/curl | xargs -i mv -f {} ./artifact/
          find ./build/busybox/bin/busybox | xargs -i mv -f {} ./artifact/
          
          
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: curl and busybox
          path: ./artifact/
